id: I5CAE50D6
legacy_id: P009410
ocr_import_info:
  bdrc_scan_id: W1KG4336
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T20:04:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:37:23.971191+00:00'
last_modified: 2022-09-01 00:38:41.060683
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4336
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4336
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་སྤུངས་དཔེ་རྙིང་གསར་བསྐྲུན་ལས་ཁྲིད་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ཀརྨ་པ ༡༥་མཁའ་ཁྱབ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6633027523666729
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I1KG4370:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4370
      total_pages: 606
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4370.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6518698260887082
    legacy_id: v001
  I1KG4371:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4371
      total_pages: 1056
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG4371.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6724690360428939
    legacy_id: v002
  I1KG4372:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4372
      total_pages: 452
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG4372.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.6978401364025169
    legacy_id: v003
  I1KG4373:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4373
      total_pages: 684
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG4373.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6250507201094669
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
