id: I5CAE50D6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T20:08:37+00:00'
last_modified: '2022-06-08T10:50:18.241465+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4336
  title: དཔལ་སྤུངས་དཔེ་རྙིང་གསར་བསྐྲུན་ལས་ཁྲིད་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DDEF:
      image_group_id: I1KG4370
      title: ''
      total_pages: 606
      order: 1
      base_file: DDEF.txt
    9EF5:
      image_group_id: I1KG4371
      title: ''
      total_pages: 1056
      order: 2
      base_file: 9EF5.txt
    '5838':
      image_group_id: I1KG4372
      title: ''
      total_pages: 452
      order: 3
      base_file: 5838.txt
    23F2:
      image_group_id: I1KG4373
      title: ''
      total_pages: 684
      order: 4
      base_file: 23F2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
